### ISSUE TITLE
Cannot set multiple schedulers

### ISSUE THREAD

**Issue by itaditya** [probot/scheduler#18]
I want to make two schedulers one which runs each hour and one which runs every week day. I couldn't find a way of doing this currently with scheduler as all it's instances will trigger `schedule.repository` event. Is this currently doable ? I did find an alternate hacky solution but it's sub-optimal. If you feel the need for this feature I can make a PR for this.

**Comment by itaditya** [comment]
Currently I have to set scheduler to trigger every hour and then using `Date.now()` to check if it end of the week

**Comment by jusx** [comment]
I second the need for this. It would be good to be able to create multiple schedules the way we can with crontabs.

**Comment by wei** [comment]
I don't have a need for this right now but from looking at the code, it should be pretty straight forward to make the changes to support multiple instances with customizable event names.
